services:

  postgres:
    image: postgres:18.4
    container_name: therapy-postgres

    environment:
      POSTGRES_DB: therapy
      POSTGRES_USER: therapy_app
      POSTGRES_PASSWORD: local_dev_only

    ports:
      - "5432:5432"

    volumes:
      - therapy_postgres_data:/var/lib/postgresql

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U therapy_app -d therapy"
        ]
      interval: 5s
      timeout: 5s
      retries: 10

  flyway:
      image: redgate/flyway:13.2.0
      profiles:
        - tools

      environment:
        FLYWAY_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
        FLYWAY_USER: ${JANUS_MIGRATOR_DB_USER}
        FLYWAY_PASSWORD: ${JANUS_MIGRATOR_DB_PASSWORD}

        FLYWAY_LOCATIONS: filesystem:/flyway/sql
        FLYWAY_DEFAULT_SCHEMA: janus_meta

        FLYWAY_CONNECT_RETRIES: 60
        FLYWAY_VALIDATE_MIGRATION_NAMING: "true"
        FLYWAY_CLEAN_DISABLED: "true"

      volumes:
        - ./db/migrations:/flyway/sql:ro

      depends_on:
        postgres:
          condition: service_healthy

volumes:
  therapy_postgres_data: